name = "zurg-serverless-dev"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (non-sensitive)
[vars]
BASE_URL = ""  # Will be auto-detected from request if empty
REFRESH_INTERVAL_SECONDS = "15"
API_TIMEOUT_SECONDS = "30"
TORRENTS_PAGE_SIZE = "1000"
HIDE_BROKEN_TORRENTS = "true"

# KV disabled for local development - uncomment and add IDs when ready
# [[kv_namespaces]]
# binding = "KV"
# id = "your_kv_namespace_id"
# preview_id = "your_preview_kv_namespace_id"
