# Personal development and production configuration
# Use this for your own deployments: wrangler deploy --config wrangler.local.toml

account_id = "0a15c5f9d39350baa992ff9f48efc1c8"
name = "zurg-serverless-dev"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false  # Disable *.workers.dev preview URL

# Development environment (default) - runs locally with wrangler dev
[vars]
API_ACCOUNT_ID = "0a15c5f9d39350baa992ff9f48efc1c8"
BASE_URL = "http://localhost:8787"
REFRESH_INTERVAL_SECONDS = "5"
API_TIMEOUT_SECONDS = "15"
TORRENTS_PAGE_SIZE = "50"
HIDE_BROKEN_TORRENTS = "false"
WORKER_NAME = "zurg-serverless-dev"

# Your development database (local development uses local DB)
[[d1_databases]]
binding = "DB"
database_name = "zurg-serverless-dev-db"
database_id = "6f592a7c-d6e4-48b1-b58f-9fb9bfe0ccb0"

# Production environment - deploy with: wrangler deploy --config wrangler.local.toml --env production
[env.production]
name = "zurg-serverless"
workers_dev = false  # Disable *.workers.dev preview URL

# Custom domain configuration
routes = [
  { pattern = "zurg.andrewe.dev", custom_domain = true }
]

# Production cron triggers
[env.production.triggers]
crons = ["0 */1 * * *"]  # Every hour

[env.production.vars]
API_ACCOUNT_ID = "0a15c5f9d39350baa992ff9f48efc1c8"
BASE_URL = "https://zurg.andrewe.dev"
REFRESH_INTERVAL_SECONDS = "15"
API_TIMEOUT_SECONDS = "30"
TORRENTS_PAGE_SIZE = "1000"
HIDE_BROKEN_TORRENTS = "true"
WORKER_NAME = "zurg-serverless"

[[env.production.d1_databases]]
binding = "DB"
database_name = "zurg-serverless-production-db"
database_id = "4f471a5a-cc69-4c17-874a-eab5ec19e756"
