name = "zurg-serverless"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (non-sensitive)
[vars]
BASE_URL = ""  # Will be auto-detected from request if empty
REFRESH_INTERVAL_SECONDS = "15"
API_TIMEOUT_SECONDS = "30"
TORRENTS_PAGE_SIZE = "1000"
HIDE_BROKEN_TORRENTS = "true"
RD_TOKEN = ""
RD_UNRESTRICT_IP = ""  #optional
STRM_TOKEN = "" #optional

# KV Namespace for caching torrents and STRM codes
# Will be automatically provisioned by "Deploy to Cloudflare" button
[[kv_namespaces]]
binding = "KV"
id = ""
preview_id = ""

# secrets can be set via: wrangler secret put SECRET_NAME
