# Template wrangler.toml for "Deploy to Cloudflare" button
# This file should work for new deployments without personal config

name = "zurg-serverless"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cron triggers for cache refresh (essential for functionality)
[triggers]
crons = ["0 */1 * * *"]  # Every hour

# Default configuration for new deployments
[vars]
# These are safe defaults - secrets will be prompted during deployment
REFRESH_INTERVAL_SECONDS = "15"
API_TIMEOUT_SECONDS = "30"
TORRENTS_PAGE_SIZE = "1000"
WORKER_NAME = "zurg-serverless"

# The Deploy button will create this database automatically
[[d1_databases]]
binding = "DB"
database_name = "zurg-serverless-db"
database_id = "" # Will be populated during deployment
